import Head from 'next/head';
import * as React from 'react';
import Button from '@mui/material/Button';

export default class MyApp extends React.Component {
  render() {
    return (
      <div>
        <Head>
          <title> E-Barn</title>
          <meta name="viewport" content="initial-scale=1, width=device-width" />
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Button variant="contained">Hello World</Button>
        </main>
      </div>
    )
  }
}